KnowledgePerHour: 8
LicenseCost: 100
ClickBaseCost: 75
UpgradeCostIncrease: 2.0
ComputerPrice: 500
MaxComputerLevel: 5
BotLicenseCost: 50
BotKnowledgeCost: 100
BandwidePrice: 200
RoomPrice: 100
MinMotherWaitDuration: 10
MaxMotherWaitDuration: 10
MotherTaskWaitDuration: 24
MinMotherTaskDuration: 1
MaxMotherTaskDuration: 5
MinBotLifeDuration: 12
MaxBotLifeDuration: 24
TimeCycleInSeconds: 2.0
SchoolDuration: 8
GoldPerClick: 10
MaxGoldPrice: 3
MinGoldPrice: 0.1
SubscriptionPrice: 15
PenalizationDuration: 24
BotGoldEarnPerHour: 10
